config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/check_in', to: 'visit#create'
  get '/check_in', to: 'visit#create'
  delete '/check_out', to: 'visit#delete'
  get '/qr', to: 'visit#toggle'
  resources :visit, only: [:update, :show]
  post '/users/:id/check_out', to: 'users#check_out', as: 'force_check_out'
  post '/users/:id/approve', to: 'users#approve', as: 'approve_user'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#delete', as: 'delete_user'

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.present? && current_user.admin?
      @visits = Visit.active
    elsif current_user.present? && !current_user.approved?
      @visits = Visit.active.approved_or_self(current_user)
    else
      @visits = Visit.active.approved
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Who's At Katy Makerspace?</h1>

<% if @visits.any? %>
    <ul class="active-visits">
        <% @visits.each do |visit| %>
            <li class="visit">
                <%= link_to user_path(visit.user) do %>
                    <%= image_tag visit.user.image.url(:thumb) %>
                    <p><%= visit.user.name.truncate(15) -%></p>
                <% end -%>
                <% if is_admin? %>
                    <div class="dropdown">
                        <button
                           class="btn btn-mini btn-danger dropdown-toggle"
                           id="admin-dropdown-<%= visit.id %>"
                           data-toggle="dropdown"><span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <% if !visit.user.approved? %>
                                <li><%= link_to "Approve", approve_user_path(visit.user), method: :post %></li>
                                <li><%= link_to "Delete", delete_user_path(visit.user), method: :delete %></li>
                            <% end %>
                            <li><%= link_to "Check out", force_check_out_path(visit.user), method: :post %></li>
                        </ul>
                    </div>
                <% end %>
            </li>
        <% end %>
    </ul>
<% else %>
    <div class="nobody-here">Nobody at the moment</div>
<% end %>

<hr/>

<div class="actions">
    <% if current_user.try(:active_visit) %>
        <%= form_for current_user.active_visit, as: 'visit', url: visit_url(current_user.active_visit) do |f| %>
            <textarea placeholder="What are you working on?"
                      name="visit[task]"
                      id="visit_task"
                      class="form-control"
                      rows="4"
                      ><%= current_user.active_visit.task %></textarea>
            <br/><%= f.submit "Submit", class: 'btn btn-primary' %>
        <% end %>
        <hr/>
        <%= link_to "I'm leaving", check_out_path, method: :delete, class: 'btn btn-danger' %>
    <% elsif current_user %>
        <%= link_to "I'm here!", check_in_path, method: :post, class: 'btn btn-primary' %>
    <% else %>
        <%= link_to image_tag('google-btn.png'), user_omniauth_authorize_path(:google_oauth2) %>
        <br/>&dash;or&dash;<br/>
        <%= link_to "Sign up with email", new_user_registration_path %><br/><br/>
        to tell people you're at the space!
    <% end %>
</div>